### ISSUE TITLE
In b2b store, user can switch from one step to another without filling the info

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-demo-theme-b2b#104]
![image](https://user-images.githubusercontent.com/1566470/96778818-0802dd80-13a1-11eb-9718-0678dd4a53a5.png)

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-5684 has been created

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-5960 has been created

**Comment by AleksandraBalabanova** [comment]
Hi @Woland2k ! 
This issue is already fixed and delivered to Demo private.
