### ISSUE TITLE
Invoice generation doesn't work on dev environment on govirto.com

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-demo-theme-b2b#20]
<img width="1411" alt="Screen Shot 2020-09-11 at 9 47 37 AM" src="https://user-images.githubusercontent.com/1566470/92951825-e0207180-f413-11ea-91be-4bef9b686420.png">

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-4854 has been created
